<?xml version="1.0" encoding="utf-8"?><testsuite errors="1" failures="0" name="pytest" skips="0" tests="1" time="0.183"><testcase classname="" file="test_record_dname.py" name="test_record_dname" time="0"><error message="collection failure">ImportError while importing test module &apos;/home/kperiyaswamy/Wapi_Pytest/GOPIKRISHNA/TEST/WAPI82_Automation/test_record_dname.py&apos;.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python2.7/site-packages/_pytest/python.py:415: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
/usr/lib/python2.7/site-packages/py/_path/local.py:650: in pyimport
    __import__(modname)
/usr/lib/python2.7/site-packages/_pytest/assertion/rewrite.py:212: in load_module
    py.builtin.exec_(co, mod.__dict__)
test_record_dname.py:8: in &lt;module&gt;
    import ib_utils.ib_NIOS as ib_NIOS
E   ImportError: No module named ib_utils.ib_NIOS</error></testcase></testsuite>